### ISSUE TITLE
HISEA/CANU Version?

### ISSUE THREAD

**Issue by JosieReinhardt** [lucian-ilie/Canu_HISEA#2]
Hello,

I am using the HISEA - canu pipeline to assemble a genome, and the HISEA step is working fine...  however I am running into an error in later steps of canu and would like to submit an issue to the Canu developers.  When I tried to get the version information (which is needed for troubleshooting), I see the folllowing: 

"Canu v0.0 (+0 commits) r0 unknown-hash-tag-no-repository-available."

So what I'd like to know, is what version of canu is this so I can include that in the issue?   Can it be updated to the most current canu version?  Or should I take the output of the first two steps and feed that into the more up to date version of canu direct from the developers for the assembly step?  

Thanks,

**Comment by nkhiste** [comment]
Hi Josie,
     The version information you see is something we have changed in Canu version file. Can you reproduce the problem with latest Canu+MHAP pipeline?

If yes, then only you can request it to fix in the Canu pipeline otherwise this the issue is already addressed in the latest version of Canu.

We plan to migrate to the latest version of Canu some time in future. BTW, can you send me the exact error and the log file generated by Canu+HISEA pipeline

Thanks

**Comment by JosieReinhardt** [comment]
Sure.  I've attached the output file.  There are a ton of additional log files produced by the program, the one the final error responds to (.../unitigging/TdalD.ovlStore.BUILDING/config.err) only includes a small amount of text: 

"Found no overlaps to sort."

[slurm-11946751.out.txt](https://github.com/lucian-ilie/Canu_HISEA/files/2203180/slurm-11946751.out.txt)

**Comment by nkhiste** [comment]
It seems after processing and trimming somehow Canu pipeline ended up removing all the data. What is the original coverage level of the data-set?
Have you also tried running Canu pipeline with low/high/normal sensitivity? Does it make any difference in the outcome?

**Comment by JosieReinhardt** [comment]
It's about 33x (you can see the histogram produced by the pipeline in the output file I attached).  So, a bit low but not super low, as described in the canu docs.

I am trying to avoid a ton of runs as we have limited cpu hours to work with.  So far I have only attempted this same job twice, with the same result each time.  I was planning to ask the canu developers for guidance on this particular error, but I need a canu version to give them.  

Can you give guidance on which version of canu this pipeline is at least based on (even though you obviously have made some changes)?

**Comment by nkhiste** [comment]
I think it should be either v1.5 or v1.4 for Canu+HISEA. You can download any release from here: https://github.com/marbl/canu/releases 

As I mentioned, they won't investigate it unless problem is reproducible with Canu pipeline so you need to download an older version and try reproducing the problem with that release.
